services:
  - type: web
    name: design-orders-backend
    env: docker
    region: oregon
    plan: free
    branch: develop
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false